// Generated by scripts/update-app-version.mjs.
// Use npm run version:pr for PR minor bumps and npm run version:commit for commit patch bumps.

enum AppVersion {
  static let major = 0
  static let minor = 6
  static let patch = 0
  static let marketingVersion = "0.6.0"
  static let bundleVersion = "0.6.0"
  static let displayVersion = "0.6.0"
}
