// Generated by scripts/update-app-version.mjs.
// Update app-version.json for major/minor changes; build scripts increment build.

enum AppVersion {
  static let major = 0
  static let minor = 1
  static let build = 13
  static let marketingVersion = "0.1"
  static let bundleVersion = "13"
  static let displayVersion = "0.1 (Build 13)"
}
